Feature/merge messaging
amido/stacks-java-module-parent pull request #2
Opened 2021-11-09 18:18 UTC by guillermogutierrez

PIpelines to deploy artifacts (binaries and archetype) to jFrog artifactory

2021-11-09 18:19 UTC, guillermogutierrez commented
/azp run

2021-11-10 10:14 UTC, radoslaw-orlowski requested changes

2021-11-10 10:14 UTC, radoslaw-orlowski commented on archetype.properties
> +artifactId=stacks-core-messaging
```suggestion
artifactId=stacks-java-module-parent
```

2021-11-10 10:21 UTC, guillermogutierrez commented
Change done

2021-11-10 10:27 UTC, radoslaw-orlowski approved these changes

2021-11-10 10:28 UTC, merged